[package]
name = "mimc-jni"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pairing_ce = "0.28.5"
lazy_static = "1.4"
ff_ce = "0.14.3"
serde = "1.0.159"